version: "3"
services:
  database:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/1.sql"

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
